# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-06 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GTapp', '0002_auto_20171206_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='details',
            new_name='password',
        ),
    ]
