# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-12 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GTapp', '0003_auto_20171206_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petition_id', models.IntegerField()),
                ('title', models.CharField(max_length=2000)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
    ]
