# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-15 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GTapp', '0004_petition'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(max_length=250)),
                ('id_str', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ('-screen_name',),
            },
        ),
    ]
