# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-15 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GTapp', '0005_twitteruser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.CharField(max_length=250)),
                ('id_str', models.CharField(max_length=250)),
                ('text', models.CharField(max_length=250)),
                ('source', models.CharField(max_length=250)),
                ('truncated', models.BooleanField(default=False)),
                ('in_reply_to_status_id_str', models.CharField(max_length=250)),
                ('in_reply_to_user_id_str', models.CharField(max_length=250)),
                ('in_reply_to_screen_name', models.CharField(max_length=250)),
                ('coordinatesNumber', models.IntegerField()),
                ('coordinates', models.CharField(max_length=250)),
                ('coordinatesType', models.CharField(max_length=250)),
                ('placeCountry', models.CharField(max_length=250)),
                ('placeCountryCode', models.CharField(max_length=250)),
                ('placeFullName', models.CharField(max_length=250)),
                ('placeID', models.CharField(max_length=250)),
                ('placeName', models.CharField(max_length=250)),
                ('placeType', models.CharField(max_length=250)),
                ('placeURL', models.CharField(max_length=250)),
                ('quoted_status_id_str', models.CharField(max_length=250)),
                ('is_quote_status', models.BooleanField(default=False)),
                ('retweeted_status', models.CharField(max_length=250)),
                ('quote_count', models.IntegerField()),
                ('reply_count', models.IntegerField()),
                ('retweet_count', models.IntegerField()),
                ('favorite_count', models.IntegerField()),
                ('hashtagsNumber', models.IntegerField()),
                ('hashtags', models.CharField(max_length=250)),
                ('urls', models.CharField(max_length=250)),
                ('urlsNumber', models.IntegerField()),
                ('user_mentionsNumber', models.IntegerField()),
                ('user_mentions', models.CharField(max_length=250)),
                ('mediaNumber', models.IntegerField()),
                ('mediaURLs', models.CharField(max_length=250)),
                ('mediaType', models.CharField(max_length=250)),
                ('symbolsNumber', models.CharField(max_length=250)),
                ('symbols', models.CharField(max_length=250)),
                ('pollsNumber', models.IntegerField()),
                ('polls', models.CharField(max_length=250)),
                ('possibly_sensitive', models.BooleanField(default=False)),
                ('filter_level', models.CharField(max_length=250)),
                ('lang', models.CharField(max_length=250)),
                ('matching_rulesNumber', models.IntegerField()),
                ('matching_rulesTag', models.CharField(max_length=250)),
                ('matching_rulesID', models.CharField(max_length=250)),
                ('twitterUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='GTapp.TwitterUser')),
            ],
            options={
                'ordering': ('collected_at',),
            },
        ),
    ]
