# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-15 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GTapp', '0006_tweets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('petition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petition', to='GTapp.Petition')),
                ('twitterUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='GTapp.TwitterUser')),
            ],
        ),
    ]
