# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-22 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GTapp', '0008_auto_20180122_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterfriend',
            name='is_translator1',
            field=models.BooleanField(default=False),
        ),
    ]
