# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-22 02:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GTapp', '0009_twitterfriend_is_translator1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitterfriend',
            old_name='is_translator1',
            new_name='is_translator2',
        ),
    ]
